
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import StoreProvider from "./StoreProvider";
import Slider from "./components/Slider";
import { Button } from "./components/ui/button";
import { AlertButton } from "./components/buttons/Buttons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          <StoreProvider>
            <Slider/>
            {/* <AlertButton/> */}
            {children}
          </StoreProvider>
        </Providers>
      </body>
    </html>
  );
}
