import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" className="bg-[#1F1F1F] text-white dark">
      <body className={inter.className}>
        <Providers>
          <StoreProvider>
          <main>
            {children}
          </main>
          </StoreProvider>
        </Providers>
      </body>
    </html>
  );
}
